global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'golang'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['docker.for.mac.host.internal:8081']